version: '3.7'
# all the containers have to declare inside services
services:
  redis:
      # image name
      image: redis:latest
      # container name
      container_name: redis
      # execute the command once start redis container
      command: [
          "redis-server",
          "--bind",
          "redis",
          "--port",
          "6379"
      ]

      ports:
        - 6379:6379
  
  postgres:
      build: db
      container_name: postgres  
      ports:
        - 5432:5432
      env_file:
        - .env