version: '1.0'

services:
  backend:
    build: ./backend/chat-app-socket-programming/.
    ports:
      - 3000:3000
    depends_on:
      - mongo

  frontend:
    build: ./frontend/chat-app-socket-programming/.
    ports:
      - 8080:8080
    depends_on:
      - backend

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
